// Import du fichier JSON des questions (à créer séparément)
// Pour l'instant, on définit les questions ici en attendant le vrai JSON

export const INSTINCTIF_QUESTIONS = [
  {
    id: 'inst_01',
    ordre: 1,
    dimension: 'noticing',
    dimension_label: 'Noticing — Conscience de base',
    question: "Dans une journée ordinaire, à quel moment remarques-tu les sensations de ton corps (tensions, fatigue, faim, chaleur, inconfort) ?",
    likert_1: "Jamais — je suis constamment dans ma tête",
    likert_2: "Rarement — seulement quand c'est très intense",
    likert_3: "Parfois — quand je m'en rappelle ou que ça m'arrête",
    likert_4: "Souvent — je fais des pauses pour vérifier",
    likert_5: "Constamment — c'est une conscience de fond",
    champ_contexte_label: "Décris ton contexte habituel (travail, transport, soirée...)",
    champ_contexte_placeholder: "Ex: Je travaille toute la journée devant un écran, je fais du transport en commun...",
    champ_exemple_label: "Raconte un moment précis aujourd'hui ou hier où tu as remarqué (ou manqué) une sensation",
    champ_exemple_placeholder: "Ex: Hier soir, je me suis rendu compte que j'avais mal au cou seulement quand j'ai voulu me coucher...",
    champ_reaction_label: "Qu'as-tu fait face à cette sensation ?",
    champ_reaction_placeholder: "Ex: J'ai ignoré et continué à travailler / J'ai fait une pause / J'ai pris un médicament...",
    hints: ["tensions", "fatigue", "faim", "chaleur", "douleur diffuse"]
  },
  {
    id: 'inst_02',
    ordre: 2,
    dimension: 'not_distracting',
    dimension_label: 'Not-Distracting — Non-évitement',
    question: "Quand ton corps envoie un signal (faim, fatigue, tension, besoin de bouger), que fais-tu ?",
    likert_1: "J'ignore systématiquement jusqu'à ce que ça soit critique",
    likert_2: "J'ignore souvent — je finis ma tâche avant",
    likert_3: "Ça dépend — j'écoute si c'est pratique",
    likert_4: "J'écoute la plupart du temps — je m'arrête",
    likert_5: "J'écoute toujours immédiatement — c'est prioritaire",
    champ_contexte_label: "Contexte où tu ignores le plus souvent ton corps",
    champ_contexte_placeholder: "Ex: Au travail quand je suis concentré, en soirée avec des amis...",
    champ_exemple_label: "Dernier signal que tu as ignoré et pourquoi",
    champ_exemple_placeholder: "Ex: J'avais faim mais j'ai continué la réunion, je ne voulais pas paraître faible...",
    champ_reaction_label: "Conséquence de l'avoir ignoré",
    champ_reaction_placeholder: "Ex: J'ai eu un coup de pompe à 16h, j'ai mangé n'importe quoi en rentrant...",
    hints: ["faim légère", "fatigue précoce", "besoin toilettes", "envie d'étirer"]
  },
  {
    id: 'inst_03',
    ordre: 3,
    dimension: 'attention_regulation',
    dimension_label: 'Attention Regulation — Focus corporel',
    question: "Peux-tu maintenir ton attention sur une sensation corporelle (respiration, pieds, cœur) pendant plusieurs minutes sans dériver vers tes pensées ?",
    likert_1: "Impossible — mon esprit dérive immédiatement",
    likert_2: "Très difficile — 30 secondes maximum",
    likert_3: "Possible avec effort — 2-3 minutes",
    likert_4: "Relativement facile — 5-10 minutes",
    likert_5: "Très facile — je ne dérive jamais",
    champ_contexte_label: "As-tu déjà une pratique de focus corporel (méditation, cohérence cardiaque...) ?",
    champ_contexte_placeholder: "Ex: Je fais 10 min de méditation parfois / Non jamais / J'ai essayé mais j'arrête...",
    champ_exemple_label: "Dernière fois que tu as essayé de rester concentré sur ton corps",
    champ_exemple_placeholder: "Ex: Ce matin en me réveillant, j'ai essayé de sentir ma respiration mais j'ai pensé à mes emails...",
    champ_reaction_label: "Ce qui fait dériver ton attention",
    champ_reaction_placeholder: "Ex: Les to-do lists, les conversations passées, la planification, l'analyse...",
    hints: ["respiration", "body scan", "cohérence cardiaque", "yoga", "marche consciente"]
  },
  {
    id: 'inst_04',
    ordre: 4,
    dimension: 'emotional_awareness',
    dimension_label: 'Emotional Awareness — Conscience émotionnelle',
    question: "Quand tu ressens une émotion forte (colère, peur, tristesse, joie), sais-tu où elle se localise dans ton corps ?",
    likert_1: "Je ne fais pas le lien — émotions et corps sont séparés",
    likert_2: "Je remarque après coup parfois",
    likert_3: "Je sais vaguement que c'est 'quelque part'",
    likert_4: "Je localise souvent précisément (ventre, poitrine, gorge...)",
    likert_5: "Je localise toujours précisément et je suis l'évolution",
    champ_contexte_label: "Dernière émotion forte ressentie",
    champ_contexte_placeholder: "Ex: Hier j'ai eu peur en recevant un email de mon client...",
    champ_exemple_label: "Où l'as-tu sentie dans ton corps ?",
    champ_exemple_placeholder: "Ex: Un nœud dans l'estomac, la gorge serrée, les mains moites, le cœur qui bat...",
    champ_reaction_label: "Comment cette sensation a évolué ?",
    champ_reaction_placeholder: "Ex: Au début c'était dans le ventre, puis ça est monté à la gorge...",
    hints: ["colère → ventre chaud", "peur → ventre/nuque", "tristesse → poitrine", "joie → cœur"]
  },
  {
    id: 'inst_05',
    ordre: 5,
    dimension: 'trusting',
    dimension_label: 'Trusting — Confiance aux signaux',
    question: "Fais-tu confiance aux signaux de ton corps pour prendre des décisions ?",
    likert_1: "Je me méfie totalement — je ne suis que l'analyse",
    likert_2: "Je me méfie souvent — l'intuition m'a déçu",
    likert_3: "Ça dépend — uniquement pour les petites décisions",
    likert_4: "J'écoute souvent — l'intuition me guide régulièrement",
    likert_5: "Je fais entière confiance — c'est mon premier filtre",
    champ_contexte_label: "Une décision récente où tu as suivi (ou ignoré) une sensation corporelle",
    champ_contexte_placeholder: "Ex: J'ai accepté un projet malgré un mauvais pressentiment dans le ventre...",
    champ_exemple_label: "Résultat de cette décision",
    champ_exemple_placeholder: "Ex: Le projet s'est mal passé, j'aurais dû écouter mon intuition / Ça a bien marché...",
    champ_reaction_label: "Une fois où tu as ignoré ton intuition et regretté",
    champ_reaction_placeholder: "Ex: J'ai signé le contrat malgré mon malaise, et j'ai eu des problèmes 6 mois après...",
    hints: ["ventre ouvert/fermé", "frissons validation", "tension alerte", "cœur léger/lourd"]
  },
  {
    id: 'inst_06',
    ordre: 6,
    dimension: 'self_regulation',
    dimension_label: 'Self-Regulation — Auto-régulation',
    question: "Utilises-tu ton corps pour te calmer ou te réguler quand tu es stressé, anxieux ou débordé ?",
    likert_1: "Jamais — je ne sais pas comment faire",
    likert_2: "Rarement — j'ignore et j'attends que ça passe",
    likert_3: "Parfois — j'ai une technique mais je l'oublie",
    likert_4: "Souvent — j'applique des techniques efficaces",
    likert_5: "Systématiquement — j'ai une boîte à outils complète",
    champ_contexte_label: "Dernière fois où tu as été stressé ou anxieux",
    champ_contexte_placeholder: "Ex: Hier matin avant une présentation, j'avais le cœur qui battait la chamade...",
    champ_exemple_label: "Qu'as-tu fait face à ce stress ?",
    champ_exemple_placeholder: "Ex: J'ai respiré profondément 3 fois / J'ai fait une marche rapide / Rien j'ai subi...",
    champ_reaction_label: "Efficacité de ce que tu as fait",
    champ_reaction_placeholder: "Ex: Ça a un peu calmé mais c'est revenu vite / Ça a très bien marché / Ça n'a rien changé...",
    hints: ["respiration profonde", "cohérence cardiaque", "marche", "touch apaisant", "posture changeante"]
  },
  {
    id: 'inst_07',
    ordre: 7,
    dimension: 'body_listening',
    dimension_label: 'Body Listening — Écoute symbolique',
    question: "Quand tu as mal quelque part (tête, dos, ventre...) ou une tension persistante, écoutes-tu ce que cette sensation essaie de te dire ?",
    likert_1: "Jamais — c'est un problème technique à traiter",
    likert_2: "Rarement — je me demande parfois mais je ne sais pas",
    likert_3: "Occasionnellement — j'essaye de comprendre",
    likert_4: "Souvent — je cherche le lien avec ma vie",
    likert_5: "Toujours — chaque sensation a un message",
    champ_contexte_label: "Une douleur ou tension récurrente actuellement",
    champ_contexte_placeholder: "Ex: J'ai souvent mal aux épaules et au cou, surtout le soir après le travail...",
    champ_exemple_label: "Si tu devais traduire cette sensation en message, ce serait",
    champ_exemple_placeholder: "Ex: 'Tu portes trop de poids' / 'Tu as besoin de t'allonger' / 'Tu refuses de voir quelque chose'...",
    champ_reaction_label: "Ce que tu fais face à cette douleur",
    champ_reaction_placeholder: "Ex: Je prends des anti-douleurs / Je me masse / Je m'allonge / J'ignore...",
    hints: ["épaules = fardeau", "ventre = intuition", "gorge = expression", "dos = soutien"]
  },
  {
    id: 'inst_08',
    ordre: 8,
    dimension: 'intuition',
    dimension_label: 'Intuition — Décision corporelle',
    question: "Te bases-tu sur des sensations viscérales (ventre, cœur, frissons) pour prendre des décisions importantes ?",
    likert_1: "Jamais — seulement sur l'analyse rationnelle",
    likert_2: "Rarement — je note mais je privilégie les faits",
    likert_3: "Parfois — j'équilibre raison et intuition",
    likert_4: "Souvent — l'intuition est mon premier filtre",
    likert_5: "Systématiquement — je décide avec le corps",
    champ_contexte_label: "Une décision récente où tu as utilisé ton intuition corporelle",
    champ_contexte_placeholder: "Ex: J'ai choisi cet appartement parce que je me sentais 'bien' dedans sans raison logique...",
    champ_exemple_label: "Quelle sensation t'a guidé ?",
    champ_exemple_placeholder: "Ex: Un oui expansif dans la poitrine, un ventre ouvert et chaud, un frisson de validation...",
    champ_reaction_label: "As-tu suivi cette intuition ? Résultat ?",
    champ_reaction_placeholder: "Ex: Oui et c'était un super choix / Non j'ai hésité et je regrette...",
    hints: ["ventre ouvert/fermé (oui/non)", "frissons validation", "cœur léger/lourd", "expansion/retrait"]
  },
  {
    id: 'inst_09',
    ordre: 9,
    dimension: 'interoceptive_clarity',
    dimension_label: 'Interoceptive Clarity — Clarté',
    question: "Peux-tu différencier précisément plusieurs sensations en même temps (ex: faim vs anxiété vs fatigue vs excitation) ?",
    likert_1: "Tout est flou — je ne sais pas ce que je ressens exactement",
    likert_2: "Je confonds souvent les sensations",
    likert_3: "Je distingue grossièrement les grandes familles",
    likert_4: "Je distingue bien la plupart des sensations",
    likert_5: "Je distingue clairement chaque sensation",
    champ_contexte_label: "Un moment récent où tu as confondu des sensations",
    champ_contexte_placeholder: "Ex: Je croyais avoir faim mais en mangeant je me suis rendu compte que j'étais anxieux...",
    champ_exemple_label: "Quelles sensations étaient mélangées ?",
    champ_exemple_placeholder: "Ex: Faim + anxiété, ou Fatigue + tristesse, ou Excitation + peur...",
    champ_reaction_label: "Comment fais-tu pour différencier ?",
    champ_reaction_placeholder: "Ex: Je ne sais pas trop / J'attends de voir si manger calme / Je respire et j'écoute...",
    hints: ["faim/anxiété", "fatigue/tristesse", "excitation/peur", "tension/coleère", "légèreté/joie"]
  },
  {
    id: 'inst_10',
    ordre: 10,
    dimension: 'self_compassion',
    dimension_label: 'Self-Compassion — Bienveillance',
    question: "Traites-tu ton corps avec bienveillance et patience, ou comme un outil à optimiser/sanctionner ?",
    likert_1: "Outil à optimiser — je suis dur quand il défaille",
    likert_2: "Plutôt outil — sévère envers ses limitations",
    likert_3: "Neutre — ni dur ni tendre",
    likert_4: "Plutôt bienveillant — compréhensif envers ses besoins",
    likert_5: "Bienveillance inconditionnelle — j'accueille tout",
    champ_contexte_label: "Dernier jugement négatif que tu as eu envers ton corps",
    champ_contexte_placeholder: "Ex: 'Je suis nul, je n'arrive pas à courir 30 min' / 'Mon ventre est trop gros'...",
    champ_exemple_label: "Ton dialogue intérieur habituel avec ton corps",
    champ_exemple_placeholder: "Ex: 'Allez bouge' / 'Tu me déçois' / 'Merci de me porter' / 'Je t'écoute'...",
    champ_reaction_label: "Ce que tu aimerais te dire à la place",
    champ_reaction_placeholder: "Ex: 'Merci corps de me supporter' / 'On va y aller doucement' / 'J'accepte tes limites'...",
    hints: ["accepter fatigue", "honorer faim", "respecter limites", "remercier corps", "parler doucement"]
  },
  {
    id: 'inst_11',
    ordre: 11,
    dimension: 'embodied_presence',
    dimension_label: 'Embodied Presence — Présence',
    question: "Te sens-tu 'dans' ton corps, ancré dans le moment présent, ou 'à côté', dans ta tête ?",
    likert_1: "Toujours dans ma tête, ailleurs, absent",
    likert_2: "Souvent ailleurs — je dois revenir",
    likert_3: "Alternance — parfois présent, parfois absent",
    likert_4: "Souvent dans mon corps — ancré ici-maintenant",
    likert_5: "Pleinement incarné — présence continue",
    champ_contexte_label: "Contexte où tu perds le plus souvent l'ancrage corporel",
    champ_contexte_placeholder: "Ex: Quand je travaille sur un problème complexe, quand je suis anxieux, en réunion...",
    champ_exemple_label: "Techniques pour revenir dans ton corps",
    champ_exemple_placeholder: "Ex: Je respire 3 fois / Je pose les pieds au sol / Je touche un objet froid / Je ne sais pas faire...",
    champ_reaction_label: "Fréquence des moments de pleine présence corporelle",
    champ_reaction_placeholder: "Ex: Quelques fois par jour / Presque jamais / Tout le temps...",
    hints: ["pieds au sol", "respiration consciente", "sensations physiques", "ici-maintenant", "arrêt fuite mentale"]
  },
  {
    id: 'inst_12',
    ordre: 12,
    dimension: 'somatic_integration',
    dimension_label: 'Somatic Integration — Intégration',
    question: "Ton corps influence-t-il ta façon de penser, décider et interagir avec les autres ?",
    likert_1: "Mon corps n'influence rien — pensée pure",
    likert_2: "Peu — principalement cognitif",
    likert_3: "Modérément — je commence à écouter",
    likert_4: "Beaucoup — le corps guide souvent",
    likert_5: "Pleinement — corps-esprit-relation intégrés",
    champ_contexte_label: "Comment ton corps influence ta pensée",
    champ_contexte_placeholder: "Ex: Quand je suis tendu, je vois tout négativement / Mon état corporel change ma créativité...",
    champ_exemple_label: "Comment ton corps influence tes décisions",
    champ_exemple_placeholder: "Ex: Je choisis mes projets selon mon énergie / Je dis non quand mon ventre se ferme...",
    champ_reaction_label: "Comment ton corps influence tes relations",
    champ_reaction_placeholder: "Ex: Je perçois les tensions avant qu'elles ne surviennent / Je sais quand quelqu'un est sincère...",
    hints: ["écoute corporelle choix", "perception autres via corps", "créativité incarnée", "décision holistique"]
  }
];

// Liste des dimensions pour référence
export const INSTINCTIF_DIMENSIONS = INSTINCTIF_QUESTIONS.map(q => ({
  id: q.dimension,
  label: q.dimension_label,
  ordre: q.ordre
}));
